services:
  consent-management-db:
    image: hlseven/consent-management-db:0.1.0
    container_name: consent-management-db
    hostname: consent-management-db
    ports:
      - "3306:3306"
    volumes:
      - consent-management-db-data:/var/lib/mysql

  consent-management-server:
    image: hlseven/consent-management-server:0.1.0
    environment:
#      - WILDFHIR_HOSTNAME=hostname - SET TO EXTERNAL HOSTNAME IF NEEDED
      - WILDFHIR_RESOURCEPURGEALLENABLED=true
      - WILDFHIR_DATABASE_HOST=consent-management-db
      - FHIR_PACKAGES=hl7.fhir.us.consent-management#0.1.0
    container_name: consent-management-server
    hostname: consent-management-server
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
    depends_on:
      - consent-management-db

volumes:
  consent-management-db-data:
